brew uninstall postgresdefault: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: <%= ENV['DATABASE_PORT'] { 5432 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: "goodnight_development"
